# Data Understanding

## Objectif

Comprendre la structure du dataset Olist avant de faire le nettoyage, l'analyse SQL et le dashboard BI.

Dans cette étape, nous allons :

- charger les fichiers CSV ;
- vérifier les dimensions des tables ;
- afficher les premières lignes ;
- comprendre les colonnes principales.

In [1]:
import pandas as pd
import os

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [2]:
DATA_PATH = "../data/raw/"

files = {
    "customers": "olist_customers_dataset.csv",
    "geolocation": "olist_geolocation_dataset.csv",
    "order_items": "olist_order_items_dataset.csv",
    "payments": "olist_order_payments_dataset.csv",
    "reviews": "olist_order_reviews_dataset.csv",
    "orders": "olist_orders_dataset.csv",
    "products": "olist_products_dataset.csv",
    "sellers": "olist_sellers_dataset.csv",
    "category_translation": "product_category_name_translation.csv"
}

dataframes = {}

for name, file in files.items():
    path = os.path.join(DATA_PATH, file)
    dataframes[name] = pd.read_csv(path)
    print(f"{name} chargé : {dataframes[name].shape[0]} lignes, {dataframes[name].shape[1]} colonnes")

customers chargé : 99441 lignes, 5 colonnes
geolocation chargé : 1000163 lignes, 5 colonnes
order_items chargé : 112650 lignes, 7 colonnes
payments chargé : 103886 lignes, 5 colonnes
reviews chargé : 99224 lignes, 7 colonnes
orders chargé : 99441 lignes, 8 colonnes
products chargé : 32951 lignes, 9 colonnes
sellers chargé : 3095 lignes, 4 colonnes
category_translation chargé : 71 lignes, 2 colonnes

In [3]:
dataframes["orders"]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00

In [4]:
for name, df in dataframes.items():
    print("\n" + "="*60)
    print(f"TABLE : {name}")
    print("="*60)
    display(df.head())

============================================================
TABLE : customers
============================================================

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

============================================================
TABLE : geolocation
============================================================

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

============================================================
TABLE : order_items
============================================================

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

============================================================
TABLE : payments
============================================================

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

============================================================
TABLE : reviews
============================================================

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

============================================================
TABLE : orders
============================================================

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

============================================================
TABLE : products
============================================================

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

============================================================
TABLE : sellers
============================================================

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

============================================================
TABLE : category_translation
============================================================

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

## Contrôle de la qualité des données

Dans cette section, nous analysons la structure de chaque table afin d'identifier les problèmes potentiels :

- types de données incorrects ;
- valeurs manquantes ;
- doublons ;
- colonnes importantes pour l'analyse BI.

In [5]:
for name, df in dataframes.items():
    print("\n" + "="*60)
    print(f"TABLE : {name}")
    print("="*60)
    print(df.info())

============================================================
TABLE : customers
============================================================
<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB
None

============================================================
TABLE : geolocation
============================================================
<class 'pandas.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  str
 4   geolocation_state            1000163 non-null  str
dtypes: float64(2), int64(1), str(2)
memory usage: 38.2 MB
None

============================================================
TABLE : order_items
============================================================
<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  str
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 6.0 MB
None

============================================================
TABLE : payments
============================================================
<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 4.0 MB
None

============================================================
TABLE : reviews
============================================================
<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  str
 4   review_comment_message   40977 non-null  str
 5   review_creation_date     99224 non-null  str
 6   review_answer_timestamp  99224 non-null  str
dtypes: int64(1), str(6)
memory usage: 5.3 MB
None

============================================================
TABLE : orders
============================================================
<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB
None

============================================================
TABLE : products
============================================================
<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.3 MB
None

============================================================
TABLE : sellers
============================================================
<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   str
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   str
 3   seller_state            3095 non-null   str
dtypes: int64(1), str(3)
memory usage: 96.8 KB
None

============================================================
TABLE : category_translation
============================================================
<class 'pandas.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     str
 1   product_category_name_english  71 non-null     str
dtypes: str(2)
memory usage: 1.2 KB
None

In [6]:
missing_summary = []

for name, df in dataframes.items():
    missing_count = df.isna().sum()
    missing_percent = (df.isna().mean() * 100).round(2)
    
    table_missing = pd.DataFrame({
        "table": name,
        "column": missing_count.index,
        "missing_count": missing_count.values,
        "missing_percent": missing_percent.values
    })
    
    table_missing = table_missing[table_missing["missing_count"] > 0]
    missing_summary.append(table_missing)

missing_summary = pd.concat(missing_summary, ignore_index=True)
missing_summary.sort_values(by=["table", "missing_percent"], ascending=[True, False])

       table                         column  missing_count  missing_percent
4     orders  order_delivered_customer_date           2965             2.98
3     orders   order_delivered_carrier_date           1783             1.79
2     orders              order_approved_at            160             0.16
5   products          product_category_name            610             1.85
6   products            product_name_lenght            610             1.85
7   products     product_description_lenght            610             1.85
8   products             product_photos_qty            610             1.85
9   products               product_weight_g              2             0.01
10  products              product_length_cm              2             0.01
11  products              product_height_cm              2             0.01
12  products               product_width_cm              2             0.01
0    reviews           review_comment_title          87656            88.34
1    reviews         review_comment_message          58247            58.70

In [7]:
duplicates_summary = []

for name, df in dataframes.items():
    duplicates_summary.append({
        "table": name,
        "rows": len(df),
        "duplicate_rows": df.duplicated().sum(),
        "duplicate_percent": round(df.duplicated().mean() * 100, 2)
    })

duplicates_summary = pd.DataFrame(duplicates_summary)
duplicates_summary

                  table     rows  duplicate_rows  duplicate_percent
0             customers    99441               0               0.00
1           geolocation  1000163          261831              26.18
2           order_items   112650               0               0.00
3              payments   103886               0               0.00
4               reviews    99224               0               0.00
5                orders    99441               0               0.00
6              products    32951               0               0.00
7               sellers     3095               0               0.00
8  category_translation       71               0               0.00

In [8]:
key_checks = {
    "customers": "customer_id",
    "orders": "order_id",
    "products": "product_id",
    "sellers": "seller_id"
}

for table, key in key_checks.items():
    df = dataframes[table]
    print(f"{table} — {key}")
    print(f"Nombre de lignes : {len(df)}")
    print(f"Valeurs uniques : {df[key].nunique()}")
    print(f"Doublons sur la clé : {len(df) - df[key].nunique()}")
    print("-"*40)

customers — customer_id
Nombre de lignes : 99441
Valeurs uniques : 99441
Doublons sur la clé : 0
----------------------------------------
orders — order_id
Nombre de lignes : 99441
Valeurs uniques : 99441
Doublons sur la clé : 0
----------------------------------------
products — product_id
Nombre de lignes : 32951
Valeurs uniques : 32951
Doublons sur la clé : 0
----------------------------------------
sellers — seller_id
Nombre de lignes : 3095
Valeurs uniques : 3095
Doublons sur la clé : 0
----------------------------------------

## Synthèse de la qualité des données

Après une première inspection, les données sont globalement exploitables pour un projet BI.

### Points positifs

- Les tables principales `orders`, `customers`, `products` et `sellers` ont des clés uniques.
- Les tables principales ne présentent pas de doublons complets.
- Les colonnes de prix sont correctement reconnues en format numérique.
- Les volumes de données sont suffisants pour une analyse e-commerce réaliste.

### Points à traiter

- Les colonnes de dates sont actuellement au format texte et devront être converties en datetime.
- Certaines commandes n'ont pas de date de livraison ou d'approbation.
- Certains produits n'ont pas de catégorie.
- La table `geolocation` contient beaucoup de doublons et ne sera pas utilisée dans la première version du dashboard.
- Les commentaires clients sont très incomplets et ne seront pas utilisés dans la première version.

### Décisions pour la suite

- Filtrer les commandes livrées pour les KPIs business principaux.
- Remplacer les catégories produits manquantes par `unknown`.
- Utiliser `customer_state` pour l'analyse régionale.
- Ne pas utiliser `geolocation` dans la première version du projet.

## 3. Conversion des colonnes de dates

Les colonnes de dates sont actuellement stockées au format texte.

Pour pouvoir analyser l'évolution des ventes dans le temps, calculer les délais de livraison et créer des agrégations mensuelles, nous devons les convertir au format datetime.

In [9]:
orders = dataframes["orders"].copy()
order_items = dataframes["order_items"].copy()
customers = dataframes["customers"].copy()
products = dataframes["products"].copy()
payments = dataframes["payments"].copy()
category_translation = dataframes["category_translation"].copy()

In [10]:
orders_date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in orders_date_columns:
    orders[col] = pd.to_datetime(orders[col], errors="coerce")

orders[orders_date_columns].dtypes

order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
dtype: object

In [11]:
order_items["shipping_limit_date"] = pd.to_datetime(
    order_items["shipping_limit_date"],
    errors="coerce"
)

order_items["shipping_limit_date"].dtype

dtype('<M8[us]')

In [12]:
orders[orders_date_columns].head()

,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26

### Résultat

Les colonnes de dates ont été converties avec succès au format datetime.

Cette conversion permettra de réaliser des analyses temporelles fiables, notamment l'évolution mensuelle du chiffre d'affaires et l'étude des délais de livraison.

## Création de la table principale des ventes

L'objectif de cette étape est de construire une table centrale appelée `sales`.

Cette table combine les informations nécessaires pour calculer les KPIs business :

- commandes ;
- produits vendus ;
- clients ;
- catégories ;
- paiements.

Dans cette table, une ligne représente un produit vendu dans une commande.

Cette structure est adaptée à l'analyse BI car elle permet d'étudier le chiffre d'affaires par mois, produit, catégorie, client et région.

Nous allons utiliser des jointures entre les tables principales du dataset Olist.

In [13]:
sales = order_items.merge(
    orders,
    on="order_id",
    how="left"
)

sales = sales.merge(
    customers,
    on="customer_id",
    how="left"
)

sales = sales.merge(
    products,
    on="product_id",
    how="left"
)

sales = sales.merge(
    category_translation,
    on="product_category_name",
    how="left"
)

payments_by_order = payments.groupby("order_id", as_index=False).agg({
    "payment_value": "sum",
    "payment_installments": "max"
})

sales = sales.merge(
    payments_by_order,
    on="order_id",
    how="left"
)

sales.shape

(112650, 29)

### Vérification de la table centrale

Après les jointures, nous vérifions la structure de la table `sales`.

L'objectif est de contrôler :

- le nombre de colonnes ;
- les types de données ;
- la présence éventuelle de valeurs manquantes après les jointures ;
- les colonnes disponibles pour les futurs KPIs.

In [14]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 29 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       112650 non-null  str
 1   order_item_id                  112650 non-null  int64
 2   product_id                     112650 non-null  str
 3   seller_id                      112650 non-null  str
 4   shipping_limit_date            112650 non-null  datetime64[us]
 5   price                          112650 non-null  float64
 6   freight_value                  112650 non-null  float64
 7   customer_id                    112650 non-null  str
 8   order_status                   112650 non-null  str
 9   order_purchase_timestamp       112650 non-null  datetime64[us]
 10  order_approved_at              112635 non-null  datetime64[us]
 11  order_delivered_carrier_date   111456 non-null  datetime64[us]
 12  order_delivered_customer_date  110196 non-null  datetime64[us]
 13  order_estimated_delivery_date  112650 non-null  datetime64[us]
 14  customer_unique_id             112650 non-null  str
 15  customer_zip_code_prefix       112650 non-null  int64
 16  customer_city                  112650 non-null  str
 17  customer_state                 112650 non-null  str
 18  product_category_name          111047 non-null  str
 19  product_name_lenght            111047 non-null  float64
 20  product_description_lenght     111047 non-null  float64
 21  product_photos_qty             111047 non-null  float64
 22  product_weight_g               112632 non-null  float64
 23  product_length_cm              112632 non-null  float64
 24  product_height_cm              112632 non-null  float64
 25  product_width_cm               112632 non-null  float64
 26  product_category_name_english  111023 non-null  str
 27  payment_value                  112647 non-null  float64
 28  payment_installments           112647 non-null  float64
dtypes: datetime64[us](6), float64(11), int64(2), str(10)
memory usage: 24.9 MB

In [15]:
sales.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english,payment_value,payment_installments
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,2017-09-13 09:45:35,2017-09-19 18:34:16,2017-09-20 23:43:48,2017-09-29,871766c5855e863f6eccc05f988b23cb,28013,campos dos goytacazes,RJ,cool_stuff,58.0,598.0,4.0,650.0,28.0,9.0,14.0,cool_stuff,72.19,2.0
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,2017-04-26 11:05:13,2017-05-04 14:35:00,2017-05-12 16:04:24,2017-05-15,eb28e67c4c0b83846050ddfb8a35d051,15775,santa fe do sul,SP,pet_shop,56.0,239.0,2.0,30000.0,50.0,30.0,40.0,pet_shop,259.83,3.0
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-01-16 12:36:48,2018-01-22 13:19:16,2018-02-05,3818d81c6709e39d06b2738a8d3a2474,35661,para de minas,MG,moveis_decoracao,59.0,695.0,2.0,3050.0,33.0,13.0,33.0,furniture_decor,216.87,5.0
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,d4eb9395c8c0431ee92fce09860c5a06,delivered,2018-08-08 10:00:35,2018-08-08 10:10:18,2018-08-10 13:28:00,2018-08-14 13:32:39,2018-08-20,af861d436cfc08b2c2ddefd0ba074622,12952,atibaia,SP,perfumaria,42.0,480.0,1.0,200.0,16.0,10.0,15.0,perfumery,25.78,2.0
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-02-16 09:46:09,2017-03-01 16:42:31,2017-03-17,64b576fb70d441e8f1b2d7d446e483c5,13226,varzea paulista,SP,ferramentas_jardim,59.0,409.0,1.0,3750.0,35.0,40.0,30.0,garden_tools,218.04,3.0

In [16]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 29 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       112650 non-null  str
 1   order_item_id                  112650 non-null  int64
 2   product_id                     112650 non-null  str
 3   seller_id                      112650 non-null  str
 4   shipping_limit_date            112650 non-null  datetime64[us]
 5   price                          112650 non-null  float64
 6   freight_value                  112650 non-null  float64
 7   customer_id                    112650 non-null  str
 8   order_status                   112650 non-null  str
 9   order_purchase_timestamp       112650 non-null  datetime64[us]
 10  order_approved_at              112635 non-null  datetime64[us]
 11  order_delivered_carrier_date   111456 non-null  datetime64[us]
 12  order_delivered_customer_date  110196 non-null  datetime64[us]
 13  order_estimated_delivery_date  112650 non-null  datetime64[us]
 14  customer_unique_id             112650 non-null  str
 15  customer_zip_code_prefix       112650 non-null  int64
 16  customer_city                  112650 non-null  str
 17  customer_state                 112650 non-null  str
 18  product_category_name          111047 non-null  str
 19  product_name_lenght            111047 non-null  float64
 20  product_description_lenght     111047 non-null  float64
 21  product_photos_qty             111047 non-null  float64
 22  product_weight_g               112632 non-null  float64
 23  product_length_cm              112632 non-null  float64
 24  product_height_cm              112632 non-null  float64
 25  product_width_cm               112632 non-null  float64
 26  product_category_name_english  111023 non-null  str
 27  payment_value                  112647 non-null  float64
 28  payment_installments           112647 non-null  float64
dtypes: datetime64[us](6), float64(11), int64(2), str(10)
memory usage: 24.9 MB

### Création d'une version propre de la table des ventes

La table `sales` contient toutes les colonnes obtenues après les jointures entre les commandes, les clients, les produits, les catégories et les paiements.

Pour faciliter l'analyse BI, nous créons une table simplifiée appelée `sales_clean`.

L'objectif est de garder uniquement les colonnes utiles pour répondre aux questions business :

- chiffre d'affaires total ;
- nombre de commandes ;
- panier moyen ;
- ventes par mois ;
- ventes par région ;
- ventes par catégorie ;
- clients fidèles ;
- analyse des délais de livraison.

Cette table propre servira ensuite pour l'analyse Python, les requêtes SQL et le dashboard Power BI.

In [17]:
sales_clean = sales[
    [
        "order_id",
        "order_item_id",
        "customer_id",
        "customer_unique_id",
        "product_id",
        "seller_id",
        "order_status",
        "order_purchase_timestamp",
        "order_approved_at",
        "order_delivered_customer_date",
        "order_estimated_delivery_date",
        "shipping_limit_date",
        "customer_city",
        "customer_state",
        "product_category_name",
        "product_category_name_english",
        "price",
        "freight_value",
        "payment_value",
        "payment_installments"
    ]
].copy()

sales_clean.shape

(112650, 20)

### Traitement des valeurs manquantes utiles

Toutes les valeurs manquantes ne doivent pas être supprimées.

Dans cette première version du projet BI, nous traitons uniquement les valeurs manquantes qui peuvent gêner directement l'analyse business.

Les catégories produits manquantes sont remplacées par `unknown`, afin de conserver les ventes associées à ces produits sans perdre de chiffre d'affaires.

In [18]:
sales_clean["product_category_name"] = sales_clean["product_category_name"].fillna("unknown")
sales_clean["product_category_name_english"] = sales_clean["product_category_name_english"].fillna("unknown")

sales_clean[["product_category_name", "product_category_name_english"]].isna().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

### Création des colonnes utiles pour l'analyse BI

Pour faciliter les analyses SQL et Power BI, nous ajoutons plusieurs colonnes calculées.

Ces colonnes permettront de calculer rapidement les KPIs business :

- chiffre d'affaires ;
- total payé avec livraison ;
- évolution mensuelle ;
- analyse annuelle ;
- délai de livraison ;
- statut de livraison.

In [20]:
sales_clean["revenue"] = sales_clean["price"]
sales_clean["total_value"] = sales_clean["price"] + sales_clean["freight_value"]

sales_clean["order_year"] = sales_clean["order_purchase_timestamp"].dt.year
sales_clean["order_month"] = sales_clean["order_purchase_timestamp"].dt.month
sales_clean["order_month_name"] = sales_clean["order_purchase_timestamp"].dt.month_name()
sales_clean["order_year_month"] = sales_clean["order_purchase_timestamp"].dt.to_period("M").astype(str)

sales_clean["delivery_days"] = (
    sales_clean["order_delivered_customer_date"] 
    - sales_clean["order_purchase_timestamp"]
).dt.days

sales_clean["is_delivered"] = sales_clean["order_status"] == "delivered"

sales_clean[
    [
        "price",
        "freight_value",
        "revenue",
        "total_value",
        "order_year",
        "order_month",
        "order_month_name",
        "order_year_month",
        "delivery_days",
        "is_delivered"
    ]
].head()

,price,freight_value,revenue,total_value,order_year,order_month,order_month_name,order_year_month,delivery_days,is_delivered
0,58.90,13.29,58.90,72.19,2017,9,September,2017-09,7.0,True
1,239.90,19.93,239.90,259.83,2017,4,April,2017-04,16.0,True
2,199.00,17.87,199.00,216.87,2018,1,January,2018-01,7.0,True
3,12.99,12.79,12.99,25.78,2018,8,August,2018-08,6.0,True
4,199.90,18.14,199.90,218.04,2017,2,February,2017-02,25.0,True

### Analyse des statuts de commande

Avant de calculer les KPIs business, nous devons vérifier les différents statuts de commande.

Cette étape permet de décider quelles commandes doivent être incluses dans l'analyse des ventes.

In [21]:
sales_clean["order_status"].value_counts()

order_status
delivered      110197
shipped          1185
canceled          542
invoiced          359
processing        357
unavailable         7
approved            3
Name: count, dtype: int64

### Filtrage des commandes livrées

Pour les KPIs business principaux, nous conservons uniquement les commandes avec le statut `delivered`.

Ce choix permet d'analyser les ventes réellement finalisées et d'éviter d'inclure les commandes annulées, indisponibles ou encore en cours de traitement.

In [22]:
sales_delivered = sales_clean[
    sales_clean["order_status"] == "delivered"
].copy()

sales_delivered.shape

(110197, 28)

### Vérification des KPIs de base

Avant d'exporter les données propres, nous calculons quelques indicateurs simples afin de vérifier que la table `sales_delivered` est cohérente.

Ces premiers KPIs permettent de contrôler rapidement le volume des ventes, le chiffre d'affaires et le panier moyen.

In [23]:
total_revenue = sales_delivered["revenue"].sum()
total_orders = sales_delivered["order_id"].nunique()
total_customers = sales_delivered["customer_unique_id"].nunique()
average_order_value = total_revenue / total_orders
total_items_sold = len(sales_delivered)

basic_kpis = pd.DataFrame({
    "KPI": [
        "Total revenue",
        "Total orders",
        "Total customers",
        "Average order value",
        "Total items sold"
    ],
    "Value": [
        round(total_revenue, 2),
        total_orders,
        total_customers,
        round(average_order_value, 2),
        total_items_sold
    ]
})

basic_kpis

                   KPI        Value
0        Total revenue  13221498.11
1         Total orders     96478.00
2      Total customers     93358.00
3  Average order value       137.04
4     Total items sold    110197.00

### Export des données propres

Après nettoyage et enrichissement, nous exportons les tables propres au format CSV.

Ces fichiers seront utilisés dans les prochaines étapes du projet :

- requêtes SQL ;
- dashboard Power BI ;
- analyses complémentaires ;
- publication GitHub.

In [24]:
CLEAN_PATH = "../data/clean/"

sales_clean.to_csv(
    os.path.join(CLEAN_PATH, "sales_clean.csv"),
    index=False
)

sales_delivered.to_csv(
    os.path.join(CLEAN_PATH, "sales_delivered.csv"),
    index=False
)

basic_kpis.to_csv(
    os.path.join(CLEAN_PATH, "basic_kpis.csv"),
    index=False
)

print("Exports terminés avec succès.")

Exports terminés avec succès.

## Conclusion

Dans ce notebook, nous avons préparé les données e-commerce Olist pour un projet Business Intelligence.

### Travail réalisé

- Chargement des fichiers CSV bruts.
- Analyse de la structure des tables.
- Vérification des types, valeurs manquantes et doublons.
- Conversion des colonnes de dates.
- Création d'une table centrale des ventes.
- Traitement des catégories produits manquantes.
- Création de colonnes utiles pour l'analyse BI.
- Filtrage des commandes livrées.
- Calcul de premiers KPIs de contrôle.
- Export des fichiers propres.

### Fichiers générés

- `sales_clean.csv`
- `sales_delivered.csv`
- `basic_kpis.csv`

Ces fichiers seront utilisés dans les prochaines étapes pour les requêtes SQL et la création du dashboard Power BI.